import agenciabrasilImg from '../assets/image/logo/agenciabrasil.png';
import aquiagoranetImg from '../assets/image/logo/aquiagoranet.png';
import camaratoledoImg from '../assets/image/logo/camaratoledo.png';
import canalruralImg from '../assets/image/logo/canalrural.png';
import catvImg from '../assets/image/logo/catv.png';
import cgnImg from '../assets/image/logo/cgn.png';
import correiodolagoImg from '../assets/image/logo/correiodolago.png';
import g1Img from '../assets/image/logo/g1.png';
import gazetadopovoImg from '../assets/image/logo/gazetadopovo.png';
import globoesporteImg from '../assets/image/logo/globoesporte.png';
import igImg from '../assets/image/logo/ig.png';
import lanceImg from '../assets/image/logo/lance.png';
import motor1Img from '../assets/image/logo/motor1.png';
import noticiasaominutoImg from '../assets/image/logo/noticiasaominuto.png';
import ofuxicoImg from '../assets/image/logo/ofuxico.png';
import oparanaImg from '../assets/image/logo/oparana.png';
import opresenteImg from '../assets/image/logo/opresente.png';
import papogulaImg from '../assets/image/logo/papogula.png';
import r7Img from '../assets/image/logo/r7.png';
import sonoticiaboaImg from '../assets/image/logo/sonoticiaboa.png';
import tecmundoImg from '../assets/image/logo/tecmundo.png';
import terraImg from '../assets/image/logo/terra.png';
import tudointeressanteImg from '../assets/image/logo/tudointeressante.png';
import uolImg from '../assets/image/logo/uol.png';
import yahooImg from '../assets/image/logo/yahoo.png';

export const agenciabrasil = agenciabrasilImg;
export const aquiagoranet = aquiagoranetImg;
export const camaratoledo = camaratoledoImg;
export const canalrural = canalruralImg;
export const catv = catvImg;
export const cgn = cgnImg;
export const correiodolago = correiodolagoImg;
export const g1 = g1Img;
export const gazetadopovo = gazetadopovoImg;
export const globoesporte = globoesporteImg;
export const ig = igImg;
export const lance = lanceImg;
export const motor1 = motor1Img;
export const noticiasaominuto = noticiasaominutoImg;
export const ofuxico = ofuxicoImg;
export const oparana = oparanaImg;
export const opresente = opresenteImg;
export const papogula = papogulaImg;
export const r7 = r7Img;
export const sonoticiaboa = sonoticiaboaImg;
export const tecmundo = tecmundoImg;
export const terra = terraImg;
export const tudointeressante = tudointeressanteImg;
export const uol = uolImg;
export const yahoo = yahooImg;